apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5000 
    targetPort: 5000
  externalIPs:
    - 80.11.12.10 
